//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarea
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Detalle { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public int IdClasificacion { get; set; }
    
        public virtual Clasificacion Clasificacion { get; set; }
    }
}
